config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  mount ActionCable.server, at: '/cable'
  resources :chats
  get '/dashboard', to: 'chats#index'
  root 'chatrooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  enum by_user: %i[admin user]
  after_create_commit { MessageBroadcastJob.perform_later self }
  after_create_commit { NotificationBroadcastJob.perform_later self }



  scope :unread_admin, -> { where(by_user: 'user', read: false) }

  belongs_to :chatroom
  validates :message, presence: true, allow_blank: false
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chats
  def info
    "#CHT0#{name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_room

  private

  def set_room
    @user = current_user
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  layout 'chat'
  
  def index
    return unless params[:info]
    @chatroom = Chatroom.find_or_create_by(name: params[:info])
    @chats = @chatroom.chats.last(50)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    render json: @chatroom.chats
  end
  
  private
  
  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!, :require_login

  def index
  end

  def create
    @chat = Chat.new(chat_params)
    respond_to do |format|
      if @chat.save
        format.json { render :show, status: :created, location: @chat }
      else
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @chat = Chat.new
  end

  def show
    @chatroom = Chatroom.find_by_id(params[:id])
    @chats = Chat.where(chatroom_id: params[:id])
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :name, :chatroom_id)
  end

  def require_login 
    redirect_to root_url  if !current_user
    if current_user
      # @chatrooms = Chatroom.joins(:chats).order('chats.created_at DESC').uniq.limit(10)


      @chatrooms = Chatroom.joins(:chats)
  .select('chatrooms.*, MAX(chats.created_at) AS latest_publication_date')
  .group('chatrooms.id')
  .order('latest_publication_date DESC')
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chatrooms/_message.html.erb
<% if message.admin? %>
    <li class="self <%= 'unread' if !message.read %>" data-token="<%= message.id %>"><%= message.message %></li>
<% else %>
    <li class="other" data-token="<%= message.id %>"><%= message.message %>
        <% if !message.read %>
            <i class="bx bx-check"></i>
        <% else %>
            <i class="bx bx-check-double"></i>
        <% end %>
    </li>
<% end %>

app/views/chatrooms/index.html.erb
<div class="floating-chat" data-info="<%= @chatroom.name %>">
    <i class="fa fa-comments" aria-hidden="true"></i>
    <div class="chat">
        <div class="header">
          <span class="title">
              Chat with support
          </span>
          <button class='close'>
              <i class="fa fa-times" aria-hidden="true"></i>
          </button>
        </div>
        <ul class="messages">
            <%= render partial: 'message', collection: @chats %>
        </ul>
        <div class="footer">
            <textarea class="text-box" data-behavior="user-help" id="message" style="resize: none;border: 0;box-shadow: none;" rows="2" ></textarea>
            <button id="sendMessage">send</button>
        </div>
    </div>
</div>

app/views/chats/_user.html.erb
<% if user.chats.any? %>
    <li class=" py-3 px-4 chat-item contacts-item" id="<%= user.id %>">
        <div class="d-flex justify-content-between align-items-center helper-chat" data-info="<%= user.id %>">
            <%= link_to chat_path(id: user.id), class: 'text-link contacts-link' do %>
                <div class="d-flex">
                    <div class=" ms-2">
                        <h5 class="mb-0"><%= user.info %></h5>
                    </div>
                </div>
            <% end %>
            <div>
                <div class="text-end">
                    <span class="icon-shape icon-xs text-white bg-danger rounded-circle fw-bold fs-6"><%= user.chats.unread_admin.count %></span>
                </div>
            </div>
        </div>
    </li>
<% end %>

app/views/chats/index.html.erb
<div class="chat-layout" id="db-wrapper">
  <main id="page-content" style="margin: 0;">
    <section class="container-fluid px-0">
      <div class="row g-0">
        <div class="col-xl-3 col-lg-12 col-md-12 col-12">
          <div class="bg-white border-end border-top vh-100">
            <div class=" chat-window">
              <div class="chat-sticky-header sticky-top bg-white">
                <ul class="nav nav-line-bottom" id="tab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active py-2" id="recent-tab" data-bs-toggle="pill" href="#recent" role="tab" aria-controls="recent" aria-selected="true">Login user</a>
                  </li>
                </ul>
              </div>
              <div data-bar="" style="height: 100vh; overflow: auto;">
                <div class="tab-content" id="tabContent">
                  <div class="tab-pane fade show active" id="recent" role="tabpanel" aria-labelledby="recent-tab">
                    <ul class="list-unstyled contacts-list">
                      <%= render partial: 'user', collection: @chatrooms %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/chats/old.html.erb
<div class="chat-layout toggled" id="db-wrapper" data-current_user="true">
  <main id="page-content" style="margin: 0;">
    <section class="container-fluid px-0">
      <div class="row g-0">
        <div class="col-xl-3 col-lg-12 col-md-12 col-12">
          <div class="bg-white border-end border-top vh-100">
            <div class=" chat-window">
              <div data-simplebar="init" style="height: 100vh; overflow: auto;" class="simplebar-scrollable-y simplebar-scrollable-x simplebar-mouse-entered">
                <div class="simplebar-wrapper" style="margin: 0px;">
                  <div class="simplebar-height-auto-observer-wrapper">
                    <div class="simplebar-height-auto-observer"></div>
                  </div>
                  <div class="simplebar-mask">
                    <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                      <div class="simplebar-content-wrapper" tabindex="0" role="region" aria-label="scrollable content"
                        style="height: 100%; overflow: scroll;">
                        <div class="simplebar-content" style="padding: 0px;">
                          <div class="tab-content" id="tabContent">
                            <div class="tab-pane fade active show" id="recent" role="tabpanel"
                              aria-labelledby="recent-tab">
                              <ul class="list-unstyled contacts-list">
                                <% @chatrooms.each do |chatroom| %>
                                  <% if chatroom.chats.any? %>
                                    <li class="bg-light py-3 px-4 chat-item contacts-item">
                                      <div class="d-flex justify-content-between align-items-center helper-chat" data-info="<%= chatroom.id %>">
                                        <%= link_to chat_path(id: chatroom.id), remote: true, class: 'text-link contacts-link' do %>
                                          <div class="d-flex">
                                            <div class=" ms-2">
                                              <h5 class="mb-0"><%= chatroom.info %></h5>
                                            </div>
                                          </div>
                                          <% end %>
                                      </div>
                                    </li>
                                  <% end %>
                                <% end %>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-9 col-lg-12 col-md-12 col-12">
          <!-- chat list -->
          <div class="chat-body w-100 vh-100 simplebar-scrollable-y" data-simplebar="init">
            <div class="simplebar-wrapper" style="margin: 0px;">
              <div class="simplebar-mask">
                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                  <div class="simplebar-content-wrapper" tabindex="0" role="region" style="    overflow: hidden scroll;"aria-label="scrollable content">
                    <div class="simplebar-content" style="padding: 0px;">
                      <div class="px-4 py-4 overflow-hidden" id='chats-info' style="height: 100%; overflow: hidden scroll;">
                      </div>
                      <div class="bg-light px-4 py-3 chat-footer mt-auto">
                        <div class="bg-white p-2 rounded-3 shadow-sm">
                            <div class="position-relative">
                              <input data-behavior="user-help" class="form-control border-0 form-control-simple no-resize"
                                placeholder="Type a New Message" rows="1">
                            </div>
                            <div class="position-absolute end-0 mt-n7 me-4">
                              <button data-send="send" class="fs-3 btn text-primary btn-focus-none">
                                <i class="fe fe-send"></i>
                              </button>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/chats/show.html.erb
<div class="chat-layout" id="db-wrapper">
  <main id="page-content" style="margin: 0;">
    <section class="container-fluid px-0">
      <div class="row g-0">
        <div class="col-xl-3 col-lg-12 col-md-12 col-12">
          <div class="bg-white border-end border-top vh-100">
            <div class=" chat-window">
              <div class="chat-sticky-header sticky-top bg-white">
                <ul class="nav nav-line-bottom" id="tab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active py-2" id="recent-tab" data-bs-toggle="pill" href="#recent" role="tab" aria-controls="recent" aria-selected="true">Login user</a>
                  </li>
                </ul>
              </div>
              <div data-bar="" style="height: 100vh; overflow: auto;">
                <div class="tab-content" id="tabContent">
                  <div class="tab-pane fade show active" id="recent" role="tabpanel" aria-labelledby="recent-tab">
                    <ul class="list-unstyled contacts-list">
                      <%= render partial: 'user', collection: @chatrooms %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-9 col-lg-12 col-md-12 col-12">
          <div class=" chat-body w-100 vh-100" >
            <div class="px-4 py-4 " style='height: 90%' id='chats-info' data-bar="">
                <%= render partial: "/shared/chat", collection: @chats  %>
            </div>
            <div class="bg-light px-4 py-3 chat-footer mt-auto">
              <div class="bg-white p-2 rounded-3 shadow-sm">
                <div class="position-relative">
                  <input data-behavior="user-help" class="form-control border-0 form-control-simple no-resize" placeholder="Type a New Message" rows="1">
                </div>
                <div class="position-absolute end-0 mt-n7 me-4">
                  <button data-send="send" class="fs-3 btn text-primary btn-focus-none">
                    <i class="fe fe-send"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>
<script>
    $(document).on('turbolinks:load', function() {
        var Approom = App.cable.subscriptions.create({
            channel: "ChatsChannel",
            room: <%= @chatroom.name.try(:to_i) %>
        }, {
            connected: function() {},
            disconnected: function() {},
            received: function(data) {
                window.simplebars()
                if (data.read){
                    if(data.by){
                        var div = $(`div[data-token=${data.token}]`)
                        var info = div.find('.info')
                        info.removeClass('bx-check')
                        info.addClass('bx-check-double')
                    }
                } else {
                    if (data.by) {
                        $('#chats-info .simplebar-content').append(`<div class="d-flex justify-content-end mb-4" data-token="${data.token}"> <div class="me-3 text-end"> <small> 09:35</small> <div class="d-flex"> <div class="card mt-2 rounded-top-md-end-0 bg-primary text-white"> <div class="card-body p-3 text-start"> <p class="mb-0 "> ${data.message}</p> </div> </div> </div><i class="info bx bx-check"></i></div> </div>`)
                    } else {
                        $('#chats-info .simplebar-content').append(`<div class="d-flex w-lg-40 mb-4 unread" data-token="${data.token}"> <div class="ms-3"> <small> 09:35</small> <div class="d-flex"> <div class="card mt-2 rounded-top-md-left-0"> <div class="card-body p-3 "> <p class="mb-0 text-dark"> ${data.message} </p> </div> </div> </div> </div> </div>`)
                        var newMessage = $(`div[data-token="${data.token}"]`)[0]
                        observer.observe(newMessage);
                        var audio = new Audio('/notification.mp3');
                        audio.play();
                    }
                }

            },
            read: function(token) { 
                this.perform('read', {
                    token: token
                });
            },
            speak: function(message) {
                return this.perform('speak', {
                    message: message
                });
            }
        });
        function sendMessage(){
            var input = $('[data-behavior~=user-help]')
            Approom.speak(input.val());
            input.val('')
        }

        $(document).on('click', '[data-send="send"]', sendMessage)
        $(document).on('keypress', '[data-behavior~=user-help]', function(event) {
            if (event.keyCode === 13) {
                sendMessage()
                event.preventDefault();
            }
        });
        $(".chat-body").addClass("chat-body-visible");
        window.simplebars()
        setTimeout( function(){
            const chatMessages = document.querySelectorAll('.unread');
            chatMessages.forEach(function(chatMessage) {
                observer.observe(chatMessage);
            });
        }, 5000)
        const observer = new IntersectionObserver(function(entries) {
            return entries.forEach(function(entry) {
                if (entry.isIntersecting) {
                entry.target.classList.remove('unread');
                entry.target.classList.add('read');
                Approom.read(entry.target.dataset.token);
                    return observer.unobserve(entry.target);
                }
            });
        });

        window.onbeforeunload = closingCode;
        function closingCode(){
            Approom.unsubscribe()
            return null;
        }
    })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="dark">
  <head>
    <title>RentMasterChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body >
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': false %>
    <%= yield %>
  </body>
</html>

app/views/layouts/chat.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html data-theme="dark" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>RentMasterChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "chat", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'chat', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta http-Equiv="Cache-Control" Content="no-cache"/>
    <meta http-Equiv="Pragma" Content="no-cache"/>
    <meta http-Equiv="Expires" Content="0"/>
    <meta name="robots" content="none"/>
    <meta name="referrer" content="no-referrer">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body >
    <%= yield %>

  </body>
</html>

app/views/shared/_chat.html.erb
<% if current_user %>
    <% if chat.user? %>
        <div class="d-flex w-lg-40 mb-4 check-chat <%= chat.read ? 'read' : 'unread' %>" data-token="<%= chat.id %>" >
            <%= render partial: "/shared/message", object: chat, locals: {is_admin: true} %>
        </div>
    <% else %>
        <div class="d-flex justify-content-end mb-4">
            <%= render partial: "/shared/message", object: chat, locals: {is_admin: false} %>
        </div>
    <% end %>
<% end %>

app/views/shared/_message.html.erb
<div class="<%= is_admin ? 'ms-3' : 'me-3 text-end' %>">
    <small><%= message.created_at.strftime("%m/%d %H:%M") %></small>
    <div class="d-flex">
        <div class="card mt-2 <%= is_admin ? 'rounded-top-md-left-0' : 'rounded-top-md-end-0 bg-primary text-white' %>">
            <div class="card-body p-3 <%= 'text-start' if !is_admin %>">
                <p class="mb-0 <%= 'text-dark' if is_admin %>">
                    <%= message.message %>
                </p>
            </div>
        </div>
    </div>
    <% if !is_admin %>
        <i class="info bx <%= message.read ? "bx-check-double" : "bx-check" %>"></i>
    <% end %>
</div>